import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import Control, { ControlParams } from "../components/Control";
import { revalidatePath } from "next/cache";

export const metadata: Metadata = {
  title: "Next JS Toy WebApp",
  description: "Generated by seoik-cho",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  // server side에서 fetch를 끝낸 후에 client로 보냄.
  const resp = await fetch("http://localhost:9999/topics", {
    next: { tags: ["collections"] },
  });
  const topics = (await resp.json()) as { id: string; title: string }[];

  const handleDelete: ControlParams["onDelete"] = async (id: string) => {
    "use server";
    await fetch(`http://localhost:9999/topics/${id}`, { method: "DELETE" });

    const path = "/";
    revalidatePath(path);
    return { method: "replace", href: path };
  };

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control onDelete={handleDelete} />
      </body>
    </html>
  );
};

export default RootLayout;
